### ISSUE TITLE
foraging jobs ignore threshold

### ISSUE THREAD

**Issue by CodeOptimist** [fluffy-mods/ColonyManager#150]
**Describe the bug**  
selected foraging thing isn't added to count filter (gear menu)

**Expected behavior**  
after selecting it on right side, should show up in filter, like with other tabs

**Steps to reproduce**  
1. forage tab
2. click &lt;New job&gt;
3. select any plant / bush / healroot
4. check count filter gear menu
5. observe it empty

**Other mods**  

I wouldn't do you dirty like that. Just HugsLib.

**Output log**  

**Save game**  

**Screenshots**  

**Environment**  
Win10 64
 
**Game**
64 Steam 1.0

**Comment by CodeOptimist** [comment]
Hold on, it's like it works one time but then it never works again? And also the filter shows something entirely different when you just open foraging tab (nothing selected, no jobs listed TO select) vs. when you click on "new job".

Uhm I'll test this more and edit it to try to give you a much better bug report tomorrow.

**Comment by dandiez** [comment]
@CodeOptimist 
I could not reproduce the bug... Did you start a new game or was this issue on an existing save?
Do you effectively see an empty dialog (the one with the clear all / allow all buttons below?)
![Untitled](https://user-images.githubusercontent.com/47832466/67636959-1de8da00-f8d6-11e9-8318-3fdddb694d77.png)

**Comment by CodeOptimist** [comment]
@dandiez New games AND existing saves. With only HugsLib and Colony Manager.
Yes.

Are you doing step 2? If you skip #2 the menu has some defaults. (Which also don't update or correspond with plant selection in the far right column and feels buggy in its own right, but never mind that.)

**Comment by FluffierThanThou** [comment]
Actually, this was working as intended, but I've now added the sync functionality to the foraging tab as well.
