### ISSUE TITLE
menu buttons 

### ISSUE THREAD

**Issue by zymex22** [fluffy-mods/ColonyManager#158]
I cant switch between menus inside the manager overlay only hunter overlay seem to work.
it does work though, and they do manage hunt =)

its just blank if i press any of the other menus, dunno if i have done something wrong,
using 1.1 version =)

**Comment by FluffierThanThou** [comment]
This may have been fixed as part of a general fix with using tagged strings to sort on. If not, please add a player_log so I can have a closer look.
