### ISSUE TITLE
UI buttons are invisible, still able to be triggered.

### ISSUE THREAD

**Issue by CoffeeFueledPanda** [fluffy-mods/ColonyManager#160]
**Describe the bug**  
I installed the mod, restarted and then at first tried it with an old save (I know, not the best idea), I then noticed that there were no buttons and decided to start a new game. First thing I tried was to open the menu, then double check I had any/all research, then tried several tables and materials, but it still wouldn't work. I then proceeded to click around the UI after looking at some screenshots and some different elements did appear, however; I get the feeling the icons are being either not loaded or are just not there. 

**Expected behavior**  
I expected there to be buttons (there are but I can't see them.

**Steps to reproduce**  
Start any game old or new, then open the ui.

**Other mods**  
Most of your mods and some others, not quite sure how to send you the entire list, besides screenshoting everything. :cry: 

**Output log**  
https://pastebin.com/YYr1Ps5B

**Save game**  
Will send the save when I figure out how to do it. :)

**Screenshots**  
![Rimworld Manager bug report](https://user-images.githubusercontent.com/22580785/75611899-dd68c980-5b1e-11ea-9531-56794965a250.png)

**Environment**  
 - Manjaro
 - 64 bit
 
**Game**
 - 64 bits
 - Steam
 - 1.1

**Comment by FluffierThanThou** [comment]
should be fixed with the latest release.

**Comment by CoffeeFueledPanda** [comment]
@FluffierThanThou ,

Thank you for all your hard work, I'll give it a whirl and keep you posted. :+1: :smiley:

**Comment by CoffeeFueledPanda** [comment]
It seems to still be there, for some weird reason another mod 'Dub's hygiene' seems to have the same issue now, it's missing some textures and is throwing the same sort of errors.

[](https://pastebin.com/JekGGm5P)
