### ISSUE TITLE
Use keyed strings for history chapter labels

### ISSUE THREAD

**Issue by dodther** [fluffy-mods/ColonyManager#161]
How to i can tranlate this?
![Без имени4](https://user-images.githubusercontent.com/15664548/75628347-d37cbe80-5c23-11ea-90aa-5c68e5ed8b9d.png)

and this...
![Без имени](https://user-images.githubusercontent.com/15664548/75628485-1be8ac00-5c25-11ea-858f-b89aecff8b4e.png)

**Comment by FluffierThanThou** [comment]
Good question. At the moment, you cannot. I'll replace them with keyed strings
